#!/bin/bash
#
# Lint Swift code with swiftlint.
#
# Pass the paths of all source folders as arguments.

if ! [ -x "$(command -v swiftlint)" ]; then
  echo 'error: swiftlint is not installed.' >&2
  exit 1
fi

for FILE in "$@"
do
  swiftlint --path $FILE --config $(dirname $0)/.swiftlint.yml
done

