#!/bin/bash
#
# Pre-commit hook that:
# 1. Formats Swift code with swiftformat
# 2. Lints Swift code and aborts the commit if there are any violations

set -e

files=$(git diff --name-only --cached --diff-filter=d)

$(dirname $0)/../run $files

# Re-add files in the index so that formatted files are added
git add $files
